www.augmint.cc corrected
Augmint/augmint-sim pull request #49
Opened 2018-02-22 21:12 UTC by lbarjak

2018-02-22 21:12 UTC, szerintedmi commented
Deploy preview for *augmintsim* processing.

Built with commit 178da9a2b8d412273d7411a6ec79c51a203838fd

https://app.netlify.com/sites/augmintsim/deploys/5a8f32470b79b7316e4a21e7

2018-02-22 21:14 UTC, szerintedmi requested changes

2018-02-22 21:14 UTC, szerintedmi commented on README.md
> +Augmint is a decentralised stable cryptocurrency on Ethereum. Read more about the concept on [www.augmint.cc](http://www.augmint.cc)
hoops, thank you.
If we are here then could we link with https:  please?

2018-02-23 12:04 UTC, szerintedmi commented
@lbarjak : thanks for the https fix.
I can't merge as it has conflicts - latest actor UI additions are missing.  You need to pull from staging and merge with conflicts resolved.

2018-02-23 13:13 UTC, szerintedmi approved these changes

2018-02-23 13:13 UTC, merged

2018-02-23 16:00 UTC, lbarjak reviewed
ok.

2018-02-23 16:00 UTC, lbarjak commented on README.md
> +Augmint is a decentralised stable cryptocurrency on Ethereum. Read more about the concept on [www.augmint.cc](http://www.augmint.cc)
Moment, please.